apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: application-services

bases:
  - ../base

namePrefix: lhk-

commonLabels:
  lang: php
  app: application

images:
  - name: http-image
    newName: registry.digitalocean.com/hero7tech/lhk-laravel-app

configMapGenerator:
  - name: configmap-envs
    behavior: merge
    literals:
      - APP_NAME=LHK
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
      - DB_CONNECTION=pgsql
      - DB_HOST=posgresql-postgresql.application-storage.svc.cluster.local
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=redis
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis
      - SESSION_LIFETIME=120
      - MEMCACHED_HOST=127.0.0.1
      - REDIS_HOST=redis-master.application-storage.svc.cluster.local
      - REDIS_PORT=6379
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS="hello@example.com"
      - MAIL_FROM_NAME=lhk
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=
      - AWS_USE_PATH_STYLE_ENDPOINT=false
      - PUSHER_APP_ID=
      - PUSHER_APP_KEY=
      - PUSHER_APP_SECRET=
      - PUSHER_APP_CLUSTER=mt1
      - MIX_PUSHER_APP_CLUSTER=us2

secretGenerator:
  - name: secrets-envs
    behavior: merge
    type: Opaque
    files:
      - APP_KEY=private/app_key.env
      - DB_USERNAME=private/db_username.env
      - DB_PASSWORD=private/db_password.env
      - REDIS_PASSWORD=private/redis_password.env
