apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml

commonLabels:
  type: http
  interface: http
  project: r8write

configMapGenerator:
  - name: configmap-envs

secretGenerator:
  - name: secrets-envs
